### ISSUE TITLE
Certificate download (wget) issues

### ISSUE THREAD

**Issue by dhartford** [hubspotdevops/puppet-nexus#50]
Last friday, 5/22/2015, certificate download issues:

Notice: /Stage[main]/Nexus::Package/Wget::Fetch[nexus-2.11.2-bundle.tar.gz]/Exec[wget-nexus-2.11.2-bundle.tar.gz]/returns: ERROR: certificate common name “a.ssl.fastly.net” doesn’t match requested host name “sonatype-download.global.ssl.fastly.net

Notice: /Stage[main]/Nexus::Package/Wget::Fetch[nexus-2.11.2-bundle.tar.gz]/Exec[wget-nexus-2.11.2-bundle.tar.gz]/returns: To connect to sonatype-download.global.ssl.fastly.net insecurely, use ‘--no-check-certificate’.

recommend adding option to the wget section to allow unvalidated/unsecure downloads for --no-check-certificate pass-thru.

**Comment by dhartford** [comment]
workaround site.pp:

class{ 'nexus':
    version    => '2.11.2',
    revision   => '06',      
 }
 
Wget::Fetch{
    nocheckcertificate => true,
}

**Comment by kenbreeman** [comment]
SSL appears to be working properly at the moment.

I would not recommend disabling SSL, it is in place for a reason. A better workaround would be to download, verify, and mirror the files to a location you control with SSL if you're concerned with reliability here.
