### ISSUE TITLE
Release v1.3.2 to forge?

### ISSUE THREAD

**Issue by tykeal** [hubspotdevops/puppet-nexus#55]
I see the metadata.json was updated to version 1.3.2 after all the updates I submitted got merged. That was nearly a month ago now. Is this going to be released to the forge anytime soon?

**Comment by tmclaugh** [comment]
@pranav, @kenbreeman The force account for hubspot is in SS.  You'll need to review the process for building and submitting.  I haven't done it in awhile.

**Comment by tykeal** [comment]
Unless you're using something to do the build / submit cycle for you the process is

From an up to date checkout, in the root of the project
1. puppet module build
2. login to forge
3. select publish from the links next to your avatar
4. press the choose file button and select the file
5. press upload

;)

**Comment by kenbreeman** [comment]
v1.3.2 has been released to Forge!

https://forge.puppetlabs.com/hubspot/nexus/readme

**Comment by tykeal** [comment]
Thanks!

**Comment by sgerhards** [comment]
Could you please also tag version 1.3.2?

**Comment by kenbreeman** [comment]
Done
