### ISSUE TITLE
Release v1.3.3 to forge?

### ISSUE THREAD

**Issue by tykeal** [hubspotdevops/puppet-nexus#57]
I see that v1.3.3 was cut a few days ago. Are we going to see a release to forge soon?

**Comment by pranav** [comment]
Released @tykeal

**Comment by tykeal** [comment]
Thanks! As an FYI one of my coworkers noticed that the tag for v1.3.3 doesn't include the metadata version bump. It should probably be retagged...

**Comment by pranav** [comment]
Good catch, updated that as well, thanks!
