### ISSUE TITLE
Tests not passing??

### ISSUE THREAD

**Issue by peterabbott** [hubspotdevops/puppet-nexus#72]
Just wanted to check if you run the spec tests, do they pass. Locally and on Travis I am getting lots of test failures. Just want to rule out my environment setup. Looks like the tests are not inline with what the code is doing??

Here is a sample of what I see
https://travis-ci.org/peterabbott/puppet-nexus/jobs/155485350

**Comment by gbloquel** [comment]
You are right, I had the same trouble as you. I have fixed them into the pull request#76.

**Comment by kenbreeman** [comment]
should be fixed now: https://github.com/hubspotdevops/puppet-nexus/pull/76

**Comment by gbloquel** [comment]
In the #76 I have created the configuration for Travis. Could you create an account on Travis and link this repository? Once done you can add a   build status into the readme.md. see https://docs.travis-ci.com/user/status-images/ for detail. Thanks to that you will see if your tests and syntax are OK after each new push.

**Comment by kenbreeman** [comment]
Added
